# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18S1qljoGJRQXWPl_O2TnOdZAr09_GOVS
"""

# !pip install kagglehub dash pyngrok scikit-learn plotly

import os
import pandas as pd
import numpy as np
import plotly.express as px

import dash
from dash import dcc, html
from dash.dependencies import Input, Output

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# For downloading the dataset from Kaggle
import kagglehub

# Importing pyngrok to expose the Dash app when running in Colab
# from pyngrok import ngrok

###########################################################
# 1. Data Loading
###########################################################

def load_data():
    """
    Downloads the latest version of the Amazon Product Reviews dataset
    using kagglehub and loads the CSV file into a pandas DataFrame.
    """
    # Downloading the dataset
    path = kagglehub.dataset_download("miriamodeyianypeter/sentiment-analysis-amazon-product-reviews")
    print("Path to dataset files:", path)

    # Finding the first CSV file in the downloaded folder
    csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
    if not csv_files:
        raise FileNotFoundError("No CSV file found in the downloaded dataset folder.")
    file_path = os.path.join(path, csv_files[0])
    df = pd.read_csv(file_path)
    return df

# Loading the dataset
df = load_data()

# dataset is large, so taking a random sample (e.g., 1000 rows) for speed.
if len(df) > 1000:
    df_sample = df.sample(1000, random_state=42).reset_index(drop=True)
else:
    df_sample = df.copy()

print(f"Using {len(df_sample)} sample reviews for clustering.")

###########################################################
# 2. Text Vectorization (TF-IDF)
###########################################################

def vectorize_text(data, column='review_body'):
    """
    Vectorizes text from the specified column using TF-IDF.

    Parameters:
      - data: pandas DataFrame containing the text data.
      - column: name of the column containing text (default is 'review_body').

    Returns:
      - X: TF-IDF feature matrix.
      - vectorizer: the fitted TfidfVectorizer instance.
    """
    vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')
    # Filling any missing review text with an empty string
    X = vectorizer.fit_transform(data[column].fillna(''))
    return X, vectorizer

# Vectorizing the review text
X, vectorizer = vectorize_text(df_sample, column='review_body')

###########################################################
# 3. Clustering and Dimensionality Reduction Functions
###########################################################

def perform_clustering(X, n_clusters):
    """
    Performs K-Means clustering on the provided feature matrix X.

    Parameters:
      - X: Feature matrix (TF-IDF in our case).
      - n_clusters: number of clusters to form.

    Returns:
      - labels: cluster labels for each sample.
      - kmeans: the fitted KMeans model.
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(X)
    labels = kmeans.labels_
    return labels, kmeans

def reduce_dimensionality(X, n_components=2):
    """
    Reduces the dimensionality of X to n_components using PCA.

    Parameters:
      - X: Feature matrix (sparse or dense).
      - n_components: number of dimensions for output (default is 2).

    Returns:
      - X_reduced: data transformed into n_components dimensions.
      - pca: the fitted PCA model.
    """
    # Converting the sparse matrix to dense format for PCA
    pca = PCA(n_components=n_components, random_state=42)
    X_reduced = pca.fit_transform(X.toarray())
    return X_reduced, pca

def compute_elbow_scores(X, k_range=range(2, 11)):
    """
    Computes inertia values for K-Means clustering over a range of cluster numbers.

    Parameters:
      - X: Feature matrix.
      - k_range: range of k (number of clusters) to evaluate.

    Returns:
      - ks: list of k values.
      - inertias: list of corresponding inertia values.
    """
    inertias = []
    ks = list(k_range)
    for k in ks:
        kmeans = KMeans(n_clusters=k, random_state=42)
        kmeans.fit(X)
        inertias.append(kmeans.inertia_)
    return ks, inertias

def compute_silhouette(X, labels):
    """
    Computes the silhouette score for the clustering.

    Parameters:
      - X: Feature matrix.
      - labels: cluster labels from clustering.

    Returns:
      - score: silhouette score (float).
    """
    score = silhouette_score(X, labels)
    return score

###########################################################
# 4. Dashboard Layout and Callbacks using Dash
###########################################################

# Initializing the Dash app
app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Clustering Dashboard: Amazon Product Reviews"),

    # Slider to select the number of clusters
    html.Div([
        html.Label("Select Number of Clusters:"),
        dcc.Slider(
            id='cluster-slider',
            min=2,
            max=10,
            step=1,
            value=3,
            marks={i: str(i) for i in range(2, 11)}
        )
    ], style={'width': '50%', 'padding': '20px'}),

    # Scatter plot visualization of clusters
    html.Div([
        dcc.Graph(id='scatter-plot')
    ]),

    # Panel for displaying cluster statistics
    html.Div([
        html.H3("Cluster Statistics"),
        html.Div(id='cluster-stats')
    ], style={'padding': '20px', 'border': '1px solid #ccc', 'margin': '10px'}),

    # Elbow method plot for determining optimal clusters
    html.Div([
        html.H3("Elbow Method Analysis"),
        dcc.Graph(id='elbow-plot')
    ], style={'padding': '20px', 'border': '1px solid #ccc', 'margin': '10px'}),

    # Displaying the silhouette score
    html.Div([
        html.H3("Silhouette Score"),
        html.Div(id='silhouette-score', style={'fontSize': 20, 'padding': '10px'})
    ], style={'padding': '20px', 'border': '1px solid #ccc', 'margin': '10px'})
])

@app.callback(
    [Output('scatter-plot', 'figure'),
     Output('cluster-stats', 'children'),
     Output('elbow-plot', 'figure'),
     Output('silhouette-score', 'children')],
    [Input('cluster-slider', 'value')]
)
def update_dashboard(n_clusters):
    """
    Callback function that updates the scatter plot, cluster statistics,
    elbow plot, and silhouette score based on the selected number of clusters.
    """
    # 1. Performing clustering on the TF-IDF features
    labels, kmeans = perform_clustering(X, n_clusters)

    # 2. Reducing dimensions for 2D visualization using PCA
    X_reduced, _ = reduce_dimensionality(X, n_components=2)

    # 3. Building a DataFrame for visualization
    viz_df = pd.DataFrame(X_reduced, columns=['PC1', 'PC2'])
    viz_df['Cluster'] = labels.astype(str)

    # Creating a scatter plot with distinct colors for each cluster
    scatter_fig = px.scatter(viz_df, x='PC1', y='PC2', color='Cluster',
                             title=f"Clustering Visualization with {n_clusters} Clusters",
                             hover_data=[viz_df.index])

    # 4. Computing cluster statistics (number of points and centroid locations)
    stats_children = []
    unique_clusters = np.unique(labels)
    for cluster in unique_clusters:
        count = np.sum(labels == cluster)
        centroid = viz_df[viz_df['Cluster'] == str(cluster)][['PC1', 'PC2']].mean().round(2)
        stats_children.append(
            html.P(f"Cluster {cluster}: {count} points, Centroid (PC1, PC2): ({centroid['PC1']}, {centroid['PC2']})")
        )

    # 5. Computing the Elbow Method plot (inertia vs. number of clusters)
    ks, inertias = compute_elbow_scores(X, k_range=range(2, 11))
    elbow_fig = px.line(x=ks, y=inertias, markers=True,
                        title="Elbow Method: Inertia vs. Number of Clusters",
                        labels={'x': 'Number of Clusters', 'y': 'Inertia'})

    # 6. Computing and displaying the silhouette score for the current clustering
    try:
        sil_score = compute_silhouette(X, labels)
        sil_score_text = f"Silhouette Score for {n_clusters} clusters: {sil_score:.3f}"
    except Exception as e:
        sil_score_text = f"Error computing silhouette score: {str(e)}"

    return scatter_fig, stats_children, elbow_fig, sil_score_text

###########################################################
# 5. Running the Dashboard using Dash and pyngrok (for Colab)
###########################################################
# from pyngrok import ngrok, conf

# # ... (other code) ...

# if __name__ == '__main__':
#     # Set the port number for the Dash app
#     port = 8050

#     # Set the auth token using pyngrok.set_auth_token
#     ngrok.set_auth_token("2srOvm28pdOZyLF20DngYt8KHZV_44qJiAzNzYA8xaFe9qW5W")

#     # Opening an ngrok tunnel to the port
#     public_url = ngrok.connect(port)
#     print("Dash app running on:", public_url)

#     # Run the Dash app
#     app.run_server(host='0.0.0.0', port=port, debug=True)

import os

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 8050))
    app.run_server(host='0.0.0.0', port=port, debug=False)
